### ISSUE TITLE
How to disable the Soft Real-Time

### ISSUE THREAD

**Issue by nightfury272** [MicrosoftDocs/windows-iot-public#4]
Hi,
SetRTCores can't be set back to 0.
Is there any way to disable the Soft Real-Time other than using UWF or reimaging to recover?

**Comment by Sars47** [comment]
Hi @nightfury272 The only way to disable Soft Real-Time today is with a reimage. We cannot support disabling Soft Real-Time by setting the real-time core count back to zero because this would ignore the rest of the configuration settings that are required to set the device up for real-time performance.
